FROM ubuntu

LABEL maintainer="test <test@gmail.com>"

ARG TZ='Asia/Shanghai'

ENV TZ $TZ
RUN echo ${TZ} > /etc/timezone

RUN cd /root;\
	git clone https://github.com/ptkey/zsky_new; \
	mv zsky_new zsky

RUN apt update \
    && apt -y install  python-dev python-pip libmysqlclient-dev \
				 psmisc net-tools lsof redis git;\	
	pip install -r requirements.txt; \ 
	mv gunicorn.sh entrypoint.sh
	


ENTRYPOINT ["sh", "/entrypoint.sh"]
