# vim:set ft=dockerfile:
FROM ubuntu:bionic



########################sphinx########################

RUN set -ex; \
	apt-get update; \
	sphinxDeps=' \
		git \
		gcc \
		g++ \
		cmake \
		libmysqlclient-dev \
		automake \
	'; \
	apt-get update; \
	apt-get install -y $sphinxDeps;
	
RUN git clone https://github.com/wenguonideshou/sphinx-jieba \
	&& cd sphinx-jieba \
	&& git submodule update --init --recursive \
	&& ./configure --prefix=/usr/local/sphinx-jieba \
	&& \cp -r cppjieba/include/cppjieba src/  \
	&& \cp -r cppjieba/deps/limonp src/  \
	&& make install \
	&& \cp -r cppjieba/dict/* /usr/local/sphinx-jieba/etc/  \
	&& cd /usr/local/sphinx-jieba/ \
	&& \cp etc/jieba.dict.utf8 etc/xdictjieba.dict.utf8 \
	&& \cp etc/user.dict.utf8 etc/xdictuser.dict.utf8 \
	&& \cp etc/hmm_model.utf8 etc/xdicthmm_model.utf8 \
	&& \cp etc/idf.utf8 etc/xdictidf.utf8 \
	&& \cp etc/stop_words.utf8 etc/xdictstop_words.utf8 
	
	
RUN apt-get -y install rabbitmq-server default-jre
	
RUN mkdir /root/config;
	
RUN git clone https://github.com/ptkey/zsky_new.git

RUN apt-get purge -y --auto-remove $sphinxDeps;
	
RUN cp zsky_new/sphinx.conf /root/config/; \	
	cp zsky_new/sphinx.sh /entrypoint.sh; \
	cp zsky_new/youseed-spider-saver.yml /root/config/; \
	cp zsky_new/youseed-spider-saver-public-1.0.0.jar /root/config/
			
	
ENTRYPOINT ["sh", "/entrypoint.sh"]


EXPOSE 9306
EXPOSE 9312

