FROM ubuntu

LABEL maintainer="test <test@gmail.com>"

ARG TZ='Asia/Shanghai'

ENV TZ $TZ
RUN echo ${TZ} > /etc/timezone
RUN apt update \
    && apt -y install  python-dev python-pip libmysqlclient-dev python-mysqldb \
				 psmisc net-tools lsof redis git
RUN cd /root \
	&& git clone https://github.com/ptkey/zsky_new.git
	
RUN cd /root/zsky_new; \ 
	pip install -r requirements.txt; \ 
	mv gunicorn.sh /entrypoint.sh
	


ENTRYPOINT ["sh", "/entrypoint.sh"]
